### ISSUE TITLE
Meldungen, wenn ein Fehler aufgetreten ist

### ISSUE THREAD

**Issue by Aersoftler** [mboskamp/BibfileGenerator#11]
Wenn ein Fehler aufgetreten ist, soll eine Meldung erscheinen.
Siehe stellen im Code ("TODO show error dialog")

**Comment by Aersoftler** [comment]
Neue Klasse für die Dialoge hinzugefügt und an allen aktuell gebrauchten Stellen eingebaut

siehe: bb57629e5b0bee26c6afa692b07203f3fa6dc334

**Comment by mboskamp** [comment]
Hab ich in den Master gemerged
