### ISSUE TITLE
BibFileGenerator komplett auf deutsch

### ISSUE THREAD

**Issue by Aersoftler** [mboskamp/BibfileGenerator#14]
Aktuell ist der BibFileGenerator noch nicht komplett auf deutsch (siehe "Save", "Load", Überschriften der Spalten,...)
Aufgabe: Alles englische deutsch machen :D 

siehe: ...\Dropbox\Software Engineering\Links und Infos zu Eclipse

Sollen die Namen der Bibtypen auch auf deutsch angezeigt werden?

**Comment by mboskamp** [comment]
Besser gleich alles internationalisieren. Sprich: Eine Datei pro Sprache, aus der die Texte je nach Sprache ausgelesen werden

**Comment by Aersoftler** [comment]
Die Spaltenüberschriften können leider nicht deutsch werden, da sonst das Programm nicht mehr richtig funktioniert
