### ISSUE TITLE
Pflichtfelder in Formular 

### ISSUE THREAD

**Issue by mboskamp** [mboskamp/BibfileGenerator#5]
- Hinweis anzeigen, wenn nicht alle Pflichtfelder ausgefüllt wurden

**Comment by Aersoftler** [comment]
Ich habe eine Möglichkeit implementiert (noch nicht comitted), bei der ich ein EntryTextfield erstellt habe, welche von dem normalen Textfield. Dadurch kann man einem Textfeld die Property "required" auf true setzten, damit das Feld als Pflichtfeld gewertet werden kann. Der Nachteil allerdings ist, dass nun der Scene Builder nicht mehr genutzt werden kann, wenn man mit diesem Feld arbeiten möchte, sprich man muss es in der (F)MXL-Datei direkt machen.. Hat jmd vllt spontan eine andere Lösung? Spätestens am Mittwoch werde ich das dann nochmal genau erklären

**Comment by Aersoftler** [comment]
Bei der Besprechung am 01.02. hat Martin den Vorschlag gemacht, dass ein Tool geschrieben wird, welches in einer .fxml-Datei automatisch ein Textfield zu einem EntryTextfield wandelt und auch wieder zurück. Die Property required müsste trotzdem noch per Hand gesetzt werden.

**Comment by Aersoftler** [comment]
Ich habe die erste Version iklusive eines Umwandlers implementiert. Dafür habe ich erstmal einen neuen Branch eröffnet, da es einige Änderungen waren. Wenn ich das "Oke" habe, werde ich den Branch in den Master mergen. Es kann sich jeder gerne das anschauen und Anmerkungen machen.

siehe 68b3b2561dfd4dfa6b04707f3e59b86dc7b7ff6e

**Comment by mboskamp** [comment]
Ein Tool brauchen wir nicht. Man kann die Custom Komponenten in SceneBuilder importieren. Ich habe das eben probiert. Das funktioniert super.

**Comment by mboskamp** [comment]
Ich habe die jar Datei gepusht. Die kann man in SceneBuilder verwenden. Der Branch ist gemerged.
