### ISSUE TITLE
Pflichtfelder als solche kenntlich machen

### ISSUE THREAD

**Issue by mboskamp** [mboskamp/BibfileGenerator#6]
- Pflichtfelder mit Stern markieren

**Comment by MatzeK105** [comment]
Hey Martin,
überprüf und bearbeite bitte noch Folgendes:

inbook.fxml -> 2x Edition
booklet.fxml -> referenz
incollection.fxml -> number

**Comment by MaddinB82** [comment]
habe alle neu strukturiert und gemäß des Latex Kompendiums (https://de.wikibooks.org/wiki/LaTeX-Kompendium:_Zitieren_mit_BibTeX#B.C3.BCcher) die required- Variablen markiert.

entsprechend sollten die Dinge, die Matze entdeckt hat, gleich mit weg gefallen sein.

Alle Variablen sind auch neu gelabelt worden. Ich habe zwar alle Labels mit dem alten Quellcode überprüft, aber eine 100% Sicherheit hab ich aktuell nicht. Wird sich bei Problemen im Betrieb ja zeigen, oder? Bin aber optimistisch.
